- name: Installing Maven 
  ansible.builtin.dnf:
    name: maven 
    state: present 

- name: Installing dependencies
  ansible.builtin.command: mvn clean package 
  args:
    chdir: /app 

- name: Renamingthe jar file 
  ansible.builtin.command: mv target/{{component}}-{{shipping_version}}.jar {{component}}.jar   
  args:
    chdir: /app