- name: Disabling Old NodeJS and Enabling NodeJS:20
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y

- name: Installing NodeJS:20 
  ansible.builtin.package:
    name: nodejs
    state: present 

- name: Installing dependencies
  community.general.npm:
    path: /app   
